import pandas as pd
from io import StringIO
from rapidfuzz import process, fuzz
from connect_gemini import estructurar_con_prompt_especifico

# 🔧 Lista provisional de artículos válidos
articulos_validos = [
    "Aceitunas Verdes N° 000 - ALOREÑA - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 000 - ALOREÑA - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 000 - ALOREÑA - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 000 - ALOREÑA - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 00 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 00 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 00 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 00 - Frasco Vidrio 2 Kg (esc)",
    "Aceitunas Verdes N° 00 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 00 - Frasco Vidrio 0,9 Kg (esc)",
    "Aceitunas Verdes N° 0 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 0 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 0 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 0 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 0 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 0 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 1 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 1 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 1 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 1 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 1 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 1 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 2 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 2 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 2 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 2 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 2 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 2 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 3 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 3 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes N° 3 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Verdes N° 3 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Verdes N° 3 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Verdes N° 3 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes Fileteadas - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Fileteadas - Balde 12 Kg (esc)",
    "Aceitunas Verdes Fileteadas - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Verdes Fileteadas - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Fileteadas - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Rodajas Rotas - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Rodajas Rotas - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes Descarozadas MAGNA N° 0000 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Descarozadas MAGNA N° 0000 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Verdes Descarozadas MAGNA N° 0000 - Frasco Vidrio 1,6 Kg (esc)",
    "Aceitunas Verdes Descarozadas MAGNA N° 0000 - Frasco Vidrio 0,80 Kg (esc)",
    "Aceitunas Verdes Descarozadas N° 0 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Descarozadas N° 0 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Verdes Descarozadas N° 0 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Descarozadas N° 0 - Frasco Vidrio 2 Kg (esc)",
    "Aceitunas Verdes Descarozadas N° 0 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Descarozadas N° 0 - Frasco Vidrio 1 Kg (esc)",
    "Aceitunas Verdes Descarozadas N° 1 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Descarozadas N° 1 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Verdes Descarozadas N° 1 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Descarozadas N° 1 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Descarozadas N° 2 - GRANEL - Precio x Kilo",
    "Aceitunas Verdes Descarozadas N° 2 - Balde 12 Kg (esc)",
    "Aceitunas Verdes Descarozadas N° 2 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Verdes Descarozadas N° 2 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Descarozadas N° 2 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - GRANEL - Precio x Kg",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - EN ACEITE - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 0 - EN ACEITE - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 1 - GRANEL - Precio x Kg",
    "Aceitunas Verdes Rellenas con Morrón N° 1 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Verdes Rellenas con Morrón N° 1 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Verdes Rellenas con Morrón N° 1 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Negras Natural N° 000 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Natural N° 000 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 000 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural N° 000 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras Natural Condimentadas N° 000 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural Condimentadas N° 000 - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Negras Natural Condimentadas N° 000 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras Natural Condimentadas N° 000 - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Negras \"Tipo GRIEGAS\" - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Negras \"Tipo GRIEGAS\" - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Negras \"Tipo GRIEGAS\" - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras \"Tipo GRIEGAS\" - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Negras Natural N° 00 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Natural N° 00 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 00 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural N° 00 - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Negras Natural N° 00 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras Natural N° 00 - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Negras Natural N° 0 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Natural N° 0 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 0 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural N° 0 - Bidón 1 KG (esc)",
    "Aceitunas Negras N° 0 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Negras N° 0 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 1 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Natural N° 1 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 1 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural N° 1 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras N° 1 - PICUAL - GRANEL - Precio x Kilo",
    "Aceitunas Negras N° 1 - PICUAL - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 2 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Natural N° 2 - Bidón 8 Kg (5 Kg esc.)",
    "Aceitunas Negras Natural N° 2 - Bidón 3 Kg (1,9 Kg esc)",
    "Aceitunas Negras Natural N° 2 - Bidón 1,5 Kg (0,9 Kg esc)",
    "Aceitunas Negras Fileteadas - GRANEL - Precio x Kilo",
    "Aceitunas Negras Fileteadas - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Negras Fileteadas - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Negras Fileteadas - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 00 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Descarozadas N° 00 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Negras Descarozadas N° 00 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 00 - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Negras Descarozadas N° 00 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 00 - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Negras Descarozadas N° 0 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Descarozadas N° 0 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Negras Descarozadas N° 0 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 0 - Frasco Vidrio 2 KG (esc)",
    "Aceitunas Negras Descarozadas N° 0 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 0 - Frasco Vidrio 1 KG (esc)",
    "Aceitunas Negras Descarozadas N° 1 - GRANEL - Precio x Kilo",
    "Aceitunas Negras Descarozadas N° 1 - Bidón 8 Kg (4 Kg esc.)",
    "Aceitunas Negras Descarozadas N° 1 - Bidón 3 Kg (1,8 Kg esc)",
    "Aceitunas Negras Descarozadas N° 1 - Bidón 1,5 Kg (0,8 Kg esc)",
    "Aceitunas Verdes con Carozo - JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Descarozadas - JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Fileteadas - JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Rellenas c/ Morron - JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras con Carozo - JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras Fileteadas - JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes con Carozo - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Descarozadas MAGNA - Frasco x 360 g",
    "Aceitunas Verdes Descarozadas - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Rellenas c/ Morron - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Verdes Rellenas c/ Morron en Aceite - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras con Carozo - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras Descarozadas - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras Condimentadas - PREMIUM JUMBALAY - Frasco x 360 g",
    "Aceitunas Negras \"Tipo GRIEGAS\" - PREMIUM JUMBALAY - Frasco x 360 g",
    "Ajies en Vinagre - JUMBALAY - Frasco x 330 g",
    "Ajies Condimentados - JUMBALAY - Frasco 330 g",
    "Berenjenas Condimentadas - JUMBALAY - Frasco x 360 g",
    "Corazon de Alcauciles al Natural - JUMBALAY - Frasco 350 g.",
    "Cebollas Caramelizadas - JUMBALAY - Frasco 330 g",
    "Cebollitas en Vinagre - JUMBALAY - Frasco x 360 g",
    "Esparragos Verdes - Frasco 330 Gr - JUMBALAY",
    "Pepinos Agridulces - JUMBALAY - Frasco 330 g",
    "Pepinos Agridulces en Rodajas - JUMBALAY - Frasco 330 g",
    "Pepinitos en Vinagre - JUMBALAY - Frasco x 360 g",
    "Pickles en Vinagre - JUMBALAY - Frasco x 360 g",
    "Pimientos Morrones Agridulces - JUMBALAY - Frasco 310 g",
    "Pimientos Morrones Enteros - JUMBALAY - Frasco x 360 g",
    "Tomates Secos Mediterraneos (ajo y albahaca) - JUMBALAY - Frasco x 200 g",
    "Tomates Secos Patagonicos (hongos y parmesano) - JUMBALAY - Frasco x 200 g",
    "Higos en Almibar - JUMBALAY - Frasco x 450 g",
    "Zapallos en Almibar - JUMBALAY - Frasco x 360 g",
    "Higos en Almibar - JUMBALAY - Frasco x 4000 g",
    "Zapallos en Almibar - JUMBALAY - Frasco x 3000 g",
    "Mermelada de Arandanos - JUMBALAY - Frasco x 450 g",
    "Mermelada de Durazno - JUMBALAY - Frasco x 450 g",
    "Mermelada de Frutilla - JUMBALAY - Frasco x 450 g",
    "Mermelada de Frutos del Bosque - JUMBALAY - Frasco x 450 g",
    "Mermelada de Higo - JUMBALAY - Frasco x 450 g",
    "Mermelada de Limon, Miel y Jengibre - JUMBALAY - Frasco x 450 g",
    "Mermelada de Manzana y Zapallo - JUMBALAY - Frasco x 450 g",
    "Mermelada de Naranja - JUMBALAY - Frasco x 450 g",
    "Mermelada de Tomate - JUMBALAY - Frasco x 450 g",
    "Mermelada de Multifruta - JUMBALAY - Frasco x 450 g",
    "Mermelada de Frutilla - JUMBALAY - Frasco x 4000 g",
    "Mermelada de Durazno - JUMBALAY - Frasco x 4000 g",
    "Mermelada de Arandanos - JUMBALAY - Frasco x 4000 g",
    "Mermelada de Frutos del Bosque - JUMBALAY - Frasco x 4000 g",
    "Mermelada de Mango y Maracuya - JUMBALAY - Frasco x 4000 g",
    "Mermelada de Arándanos - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Durazno - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Frutilla y Arandanos - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Frutos del Bosque - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Mango y Maracuya - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Mora - Light - JUMBALAY - Frasco x 450 g",
    "Mermelada de Durazno - Light - JUMBALAY - Frasco x 4000 g",
    "Miel Natural de Abejas - JUMBALAY - Frasco x 250 Grs",
    "Miel Natural de Abejas - JUMBALAY - Frasco x 500 Grs",
    "Alcaparras - Frasco 500 Gr - JUMBALAY",
    "Alcaparras - Frasco 65 Gr - JUMBALAY",
    "Ajíes en Vinagre - JUMBALAY - Frasco Vidrio de 2900 g",
    "Berenjenas Condimentadas - JUMBALAY - Frasco Vidrio 1,5 Kg",
    "Berenjenas Condimentadas - JUMBALAY - Frasco Vidrio 2,7 Kg",
    "Cebollitas en Vinagre - GRANEL (Bidón 185 Kg) - Precio x Kilo",
    "Cebollitas en Vinagre - Bidón 5 Kg.",
    "Cebollitas en Vinagre - Bidón 2 Kg.",
    "Cebollitas en Vinagre - Frasco Vidrio 2 Kg.",
    "Cebollitas en Vinagre - Bidón 1 Kg.",
    "Cebollitas en Vinagre - Frasco Vidrio 1 Kg.",
    "Corazon de Alcauciles al Natural - JUMBALAY - Frasco Vidrio 2,8 Kg.",
    "Corazon de Alcauciles al Natural - JUMBALAY - Lata 2,5 Kg.",
    "Corazon de Alcauciles al Natural - JUMBALAY - Frasco Vidrio 1,5 Kg.",
    "Esparragos Verdes - Frasco 800 Gr - JUMBALAY",
    "Pepinos Agridulces Enteros - JUMBALAY - Frasco Vidrio 3,0 Kg.",
    "Pepinos Agridulces en Rodajas - JUMBALAY - Frasco 3,0 Kg.",
    "Pepinitos en Vinagre - GRANEL (Bidón 180 KG) - Precio x Kilo",
    "Pepinitos en Vinagre - Bidón 5 Kg.",
    "Pepinitos en Vinagre - Bidón 2 Kg.",
    "Pepinitos en Vinagre - Frasco Vidrio 2 Kg.",
    "Pepinitos en Vinagre - Bidón 1 Kg.",
    "Pepinitos en Vinagre - Frasco Vidrio 1 Kg.",
    "Pickles en Vinagre - GRANEL - Precio x Kilo",
    "Pickles en Vinagre - Bidón 5 Kg.",
    "Pickles en Vinagre - Bidón 2 Kg.",
    "Pickles en Vinagre - Frasco Vidrio 2 Kg.",
    "Pickles en Vinagre - Bidón 1 Kg.",
    "Pickles en Vinagre - Frasco Vidrio 1 Kg.",
    "Cebollas Caramelizadas - JUMBALAY - Frasco 1,5 Kg.",
    "Cebollas Caramelizadas - JUMBALAY - Frasco 3,0 Kg.",
    "Pimientos Morrones Agridulces - JUMBALAY - Frasco 3,0 Kg.",
    "Pimientos Morrones Enteros - JUMBALAY - Frasco Vidrio 2,8 Kg.",
    "Acelga Cortada 350 grs - La Banda",
    "Acelga Cortada 800 grs - La Banda",
    "Chauchas Cortadas Med. 350 grs. - La Banda",
    "Chauchas Cortadas Med. 800 grs. - La Banda",
    "Corazones de Alcauciles Enteros 400 grs. - La Banda",
    "Esparragos Blancos Enteros x 430 Es. 269 - La Banda",
    "Espinaca al Natural 350 grs. - La Banda",
    "Espinaca Cortada 800 grs. - La Banda",
    "Jardinera de Hor. y Leg. 350 grs. - La Banda",
    "Remolacha en Rebanada 350 grs. - La Banda",
    "Remolacha en Rebanadas 850 g. - La Banda",
    "Champiñones Enteros 2840 grs - La Banda",
    "Champiñones Enteros 850 grs. - La Banda",
    "Champignon Entero 750 grs. - Finca de Santiago",
    "Champiñones Enteros 400 grs. - Morixe",
    "Champiñones Enteros 400 grs. - La Banda",
    "Champiñones Enteros 400 grs. - Cumana",
    "Champignon Laminado - Bidón 8 Kg - Guajira",
    "Champignon Laminado - Bidón 3 Kg - Guajira",
    "Champignon Laminado 2840 grs. - Cumana",
    "Champignon Laminado 850 grs. - Finca de Santiago",
    "Champignon Laminado 850 grs. - Cumana",
    "Champignon Laminado 400 grs. - Cumana",
    "Champignon Laminado 284 grs. - Cumana",
    "Champiñon en Trozos 2550 grs - La Banda",
    "Champiñones Trozos 850 grs. - La Banda",
    "Champiñones Trozo 400 grs. - Morixe",
    "Champiñones Trozo 400 grs. - Cumana",
    "Champiñones Trozos 400 grs. - La Banda",
    "Choclo Grano Entero Amarillo 2950 grs. - Inalpa",
    "Choclo Grano Entero Amarillo 2130 grs. - Cumaná",
    "Choclo Grano Entero Amarillo 810 grs. - La Banda",
    "Choclo Grano Entero Amarillo 810 grs. - Cumaná",
    "Choclo Grano Entero Amarillo 350 grs. (Arg / Bsil) - La Banda",
    "Choclo Grano Entero Amarillo 300 grs. - Cumaná",
    "Choclo Amarillo Cremoso 800 grs. - La Banda",
    "Choclo Amarillo Cremoso 850 grs. - Inalpa",
    "Choclo Amarillo Cremoso 350 grs. - La Banda",
    "Choclo Amarillo Cremoso 300 grs. - Inalpa",
    "Choclo Amarillo Cremoso 300 grs. - Spat",
    "Choclo Blanco Cremoso 800 g. - La Banda",
    "Choclo Blanco Cremoso 340 g. - La Banda",
    "Arvejas Secas Rem. de 350 grs.. - La Banda",
    "Arvejas Secas Rem. de 850 grs. - La Banda",
    "Garbanzos Secos Rem. 350 grs. - La Banda",
    "Lentejas Secas Rem. 350 grs. - La Banda",
    "Puré de Garbanzo \"Hummus\" - Cristo de Los Cerros - Frasco 320 g",
    "Porotos Alubia S. Rem. 350 grs. - La Banda",
    "Porotos Alubia S. Rem. 300 grs. - Inalpa",
    "Porotos Pallares S. Rem. 350 grs. - La Banda",
    "Porotos Negros 350 grs. - La Banda",
    "Porotos Rojos 350 grs. - La Banda",
    "Cerezas Rojas en almibar - Helios - Frasco 160 Gr.",
    "Cerezas Rojas al Marrasquino - ABETO - Lata 3 Kg.",
    "Coctel de Frutas 850 grs. (4 Frutas) - La Banda",
    "Coctel de Frutas 820 grs. (5 frutas) - Cumaná",
    "Higos en Almibar - BARI - Lata 3,1 Kg",
    "Peras en mitades x 820 grs - Comai",
    "Peras en almibar 850 grs - La Banda",
    "Anana en Rodajas x 820 - La Banda",
    "Anana en Rodajas x 850 - Cumana",
    "Anana en Rodajas x 850 - STRONGER",
    "Duraznos en mitades 2900 grs. - Cumaná",
    "Duraznos en mitades 2900 grs. - Elisa",
    "Duraznos en trozos 2900 grs. - Elisa",
    "Duraznos en almibar en mitades 850 grs. - La Banda",
    "Duraznos en almibar en mitades 850 grs. - Rio Salado",
    "Duraznos en almibar en mitades 820 grs. - Alco",
    "Duraznos en almibar en mitades 820 grs. - Cumaná",
    "Palmitos Enteros 800 grs. - Vilar",
    "Palmitos Enteros 800 grs. - Cumana",
    "Palmitos Enteros 400 grs. - Morixe",
    "Palmitos Enteros 400 grs. - Vilar",
    "Palmitos Enteros 400 grs. - Cumana",
    "Palmitos Enteros 400 grs. - Siete Lagos",
    "Palmitos Trozos 800 grs. - Bajo en Sodio - Siete Lagos",
    "Palmitos Trozos 800 grs. - Vilar",
    "Palmitos Trozos 800 grs. - Cumana",
    "Palmitos Trozos 800 grs. - Sierra Leona",
    "Palmitos Trozo 400 grs. - Morixe",
    "Palmitos Trozos 400 grs. - Cumana",
    "Jalapeños - Los Montes - Frasco Vidrio 660 CC.",
    "Jalapeños - Los Montes - Frasco Vidrio 360 CC.",
    "Pim. Morrones Enteros 2500 grs. - La Banda",
    "Pim. Morrones Enteros 2500 grs. - Salvita",
    "Pim. Morrones Enteros 2500 grs. - Campo Solco",
    "Pim. Morrones Enteros 2500 grs. - Alpachiry",
    "Pim. Morrones Enteros Premium 800 Grs - JUMBALAY",
    "Pim. Morrones Enteros 800 grs. - La Banda",
    "Pim. Morrones Enteros 800 grs. - Salvita",
    "Pim. Morrones Enteros 800 grs. - Alpachiry",
    "Pim. Morrones Enteros 780 grs.- Rey De Reyes",
    "Extracto de Tomate - Lata x 150 Grs - OTITO",
    "Pure de Tomates x 520 g - ALCO ((caja x 12 u))",
    "Pure de Tomates x 530 g - DE LA HUERTA Baggio ((caja x 12 u))",
    "Pure de Tomates x 1030 g - DE LA HUERTA Baggio ((caja x 8 u))",
    "Salsa de Tomate Sachet x 2 Kg - Finca de Santiago - Caja x 4 unidades",
    "Tomates Triturados Premium 8 Kgs. (SIN TACC) - Litografia JUMBALAY",
    "Tomates Triturados 8 kgs. - Corper",
    "Tomates Triturados 8 kgs. - Alpachiry",
    "Tomates Triturados 8 kgs. - La Banda",
    "Tomate Triturado Sachet x 2 Kg - Corper - Caja x 8 unidades",
    "Tomate Triturado Sachet x 2 Kg - Finca de Santiago - Caja x 4 unidades",
    "Tomate Triturado Botella 1 litro - JUMBALAY",
    "Tomate Triturado Botella 1 litro - Corper",
    "Tomate Triturado Botella 1 litro - El Gallego",
    "Tomates Pelados Peritas Enteros 2550 grs. - La Banda",
    "Tomates Pelados Peritas Enteros 2950 grs - Corper",
    "Tomates Pelados Peritas Enteros 2930 grs - JUMBALAY",
    "Tomates Pelados Peritas Enteros 2930 grs - Elisa",
    "Tomates Pelados Peritas Enteros 2930 grs - Alco",
    "Tomate Pelado Perita Entero 400 grs. - Cumana",
    "Tomate en polvo deshidr. x 750 Grs - KNORR",
    "Anchoas - El Bocarte - Frasco de 1200 g",
    "Anchoas - Veraz - Frasco de 1000 g",
    "Anchoas - El Bocarte - Frasco en Sobres 60x3",
    "Atún Desm. Aceite y Agua 170 g - La Banda",
    "Atún Desm. Aceite y Agua 170 g. - Cumaná",
    "Atún Desmenuzado Agua 170 g. - La Banda",
    "Atún Desmenuzado Agua 170 g. - Cumaná",
    "Atún Lomitos Aceite 170 g. \"Etiqueta Negra\" - La Banda",
    "Atún Lomitos Aceite 170 g. - Siete Lagos",
    "Atún Lomitos Aceite 170 g. - Cumaná",
    "Atún Lomitos Agua 170 grs. - La Banda",
    "Atún Lomitos Agua 170 grs. - Siete Lagos",
    "Atún Lomitos Agua 170 grs. - Cumaná",
    "Atún Lomitos AGUA 1800 grs - La Banda",
    "Atún Lomito AGUA 1800 grs - Cumaná",
    "Atún Lomitos ACEITE 1800 grs - La Banda",
    "Atún Lomitos ACEITE 1250 Grs - Marbella",
    "Atún Lomito en ACEITE 1800 grs - Cumaná",
    "Caballa Aceite x 380 grs - La Banda",
    "Caballa Agua x 380 grs - La Banda",
    "Sardinas Aceite y Agua Orig Tailandia - La Banda",
    "Dulce de Batata / Vainilla - ORIETA - Cajón x 5 Kg",
    "Dulce de Batata / Vainilla c/Cacao - ORIETA - Cajón x 5 Kg",
    "Dulce de Batata / Vainilla - ESNAOLA - Lata x 5 Kg",
    "Dulce de Batata / Vainilla c/Cacao - ESNAOLA - Lata x 5 Kg",
    "Dulce de Membrillo - ILLAPEL - Cajon x 5 Kg",
    "Dulce de Membrillo - ORIETA - Cajon x 5 Kg",
    "Dulce de Membrillo - ESNAOLA - Lata x 5 Kg",
    "Mermelada de Durazno - ABEDUL - (( Caja x 108 blister x 20 Grs ))",
    "Mermelada de Frutilla - ABEDUL - (( Caja x 108 blister x 20 Grs ))",
    "Mermelada de Ciruela - ABEDUL - (( Caja x 108 blister x 20 Grs ))",
    "Mermelada de Frutos Rojos - ABEDUL - (( Caja x 108 blister x 20 Grs ))",
    "Miel industrial - NUTRIMIEL - Balde x 5,5 Kg",
    "Aceite Olivado - Don Hugo - Bidón 5 Lt.",
    "Aceite de Oliva Extra Virgen - Sabor Pampeano - Bidón Pet 5 Lts.",
    "Aceite de Oliva Extra Virgen - FINCA LA SEIS - Bidón Pet 5 Lts.",
    "Aceite de Oliva Extra Virgen - Sabor Pampeano - Bidón Pet 3 Lts.",
    "Aceite de Oliva Extra Virgen - FINCA LA SEIS - Bidón Pet 2 Lts.",
    "Aceite de Oliva Extra Virgen - Sabor Pampeano - Botella Vidrio 500 Cm3.",
    "Aceite de Oliva Extra Virgen - FINCA LA SEIS - Botella Vidrio 500 Cm3.",
    "Aceite de Oliva Extra Virgen - Sabor Pampeano - Botella Vidrio 250 Cm3.",
    "Aceite de oliva comun - Pet 500 Cm3 - Enrico Baronese",
    "Aceite de oliva -individual x 8cc x 200unid. - Enrico Baronese",
    "Aceite de Girasol 8 cc x 198 unid - ABEDUL",
    "Rocio Vegetal Girasol NATURA - *(pack 12 u x 120 g)*",
    "Rocio Vegetal Girasol NATURA x 120 g",
    "Cocinero Fritolim Clasico *(pack 12 u x 120 g)*",
    "Cocinero Fritolim Clasico x 120 g",
    "Aceite X 5 LITROS NATURA GIRASOL",
    "Aceite X 5 LITROS Alsamar GIRASOL",
    "Aceite X 5 LITROS Lagrimas del Sol GIRASOL",
    "Aceite X 5 LITROS Cañuelas GIRASOL",
    "Aceite x 10 LITROS Don Hugo GIRASOL",
    "Aceite x 10 LITROS Don Hugo GIRASOL \"Exportacion\"",
    "Aceite GIRASOL - DOS SOLES",
    "Aceite X 5 LITROS - Fritomac",
    "Aceite X 5 LITROS Lagrimas del Sol ALTO OLEICO",
    "Aceite de Maiz x 5 litros",
    "Aceite de Maiz 8cc x 200 unid - Enrico Baronese",
    "Vinagre de Alcohol x 5 lts - Menoyo",
    "Vinagre de Alcohol x 5 lts - Don Hugo",
    "Vinagre de Arroz x 1 lt - CASALTA",
    "Vinagre de Vino x 5 lts - Enrico Baronese",
    "Vinagre de Vino x 5 lts - FINCA AREZZO",
    "Vinagre de Manzana x 5 lts - Menoyo",
    "Vinagre de Manzana x 5 lts - Enrico Baronese",
    "Vinagre de Alcohol - 500cc- Pet - FINCA AREZZO",
    "Vinagre de Vino -500cc- Pet - FINCA AREZZO",
    "Vinagre de Manzana -500cc- Pet - FINCA AREZZO",
    "Vinagre de Manzana - 8cc x 200 unid - Enrico Baronese",
    "Aceto Balsámico - Bidón Pet 5 Lt. - Enrico Baronese",
    "Aceto Balsámico - Bidón Pet 5 Lt. - Don Hugo",
    "Aceto Balsámico - Bidón Pet 3 Lt. - CASALTA",
    "Aceto Balsamico - Sabor Pampeano - Botella Vidrio 250 Cm3.",
    "Aceto Balsámico - 500CC - pet - FINCA AREZZO",
    "Aceto Balsámico Clasico - 400 CC - pet - CASALTA",
    "Aceto Balsámico REDUCCION - 500CC - pet - Enrico Baronese",
    "Aceto Balsámico tipo Reduccion - 400 CC - pet - CASALTA",
    "Aceto Balsámico 8cc x 200 unid - Enrico Baronese",
    "Salsa de soja- 500CC- Pet - FINCA AREZZO",
    "Salsa de soja Cremosa - 500CC- Pet - FUMEIGA",
    "Salsa de Soja - 200 Sobres x 8cc - Enrico Baronese",
    "Salsa de soja- 5 Lts - Enrico Baronese",
    "Jugo de Limón - 500 cc- Pet - FINCA AREZZO",
    "Jugo de Limon - 500 cc - Minerva",
    "Jugo de Limón - 1000 cc - Pet - Enrico Baronese",
    "Jugo de Limon - 1 Lt - Minerva",
    "Jugo de Limón - 8cc x 200 unid - Enrico Baronese",
    "Humo Liquido - Botella 1 Lt - Quinto Sabor",
    "AjiNoMoto - Bolsa x 1 Kg",
    "Salsa Pimenta Tabasco x 60 g - CHOVI",
    "Salsa Demi Glace x 1 Kg - Knorr",
    "Salsa Demi Glace x 480 Grs - Safra",
    "Salsa Blanca x 880 Grs - Knorr",
    "Aderezo CAESAR HELLMANN´S 90 x 20 Grs sobresitos",
    "Aderezo CAESAR x 950 Grs - HELLMANN´S",
    "Aderezo CAESAR - Doy Pack x 950 Grs - Tau Delta",
    "Salsa Alioli X 3 Kg - Dos Anclas",
    "Mayonesa DP x 350 Gr - HEINZ ((caja x 12 unid))",
    "Mayonesa NATURA - Caja 192 sobrecitos X 8 Grs",
    "Mayonesa HELLMANN`S clasica 196 x 7,6 Grs sobrecitos",
    "Mayonesa NATURA X 3 Kg",
    "Mayonesa CADA DIA X 3 Kg",
    "Mayonesa HELLMANN`S clasica x 2,75 Kg",
    "Mostaza Relish - Los Montes - Frasco Vidrio 3000 CC.",
    "Mostaza Relish - Los Montes - Frasco Vidrio 200 CC.",
    "Mostaza Dijon - Los Montes - Frasco Vidrio 3000 CC.",
    "Mostaza x 227 Gr - HEINZ ((caja x 12 unid))",
    "Mostaza NATURA - Caja 192 sobrecitos X 8 Grs",
    "Mostaza SAVORA 196 x 8 Grs sobrecitos",
    "Mostaza SAVORA X 3 Kg",
    "Mostaza NATURA X 3 Kg",
    "Ketchup Pet x 397 Gr - HEINZ ((Caja x 16 unid))",
    "Ketchup HELLMANN`S 196 x 8 Grs sobrecitos",
    "Ketchup NATURA - Caja 192 sobrecitos X 8 Grs",
    "Ketchup HEINZ x 3,23 Kg",
    "Ketchup NATURA X 3 Kg",
    "Ketchup HELLMANN`S X 3 Kg",
    "Barbacoa HELLMANN`S X 1 Kg",
    "Barbacoa TAU DELTA X 1 Kg",
    "Barbacoa TAU DELTA X 3 Kg",
    "Barbacoa HELLMANN`S X 3 Kg",
    "Teriyaki TAU DELTA X 1 Kg - Doy Pack",
    "Salsa Golf NATURA 192 x 8 Grs sobrecitos",
    "Salsa Golf HELLMANN`S 196 x 8 Grs sobrecitos",
    "Salsa Golf HELLMANN`S X 950 Gr",
    "Salsa Golf NATURA X 3 Kg",
    "Salsa Alioli x 340 Gr - Dos Anclas",
    "Aderezo Caesar TAU DELTA x 330 Gr",
    "Aderezo Caesar Light TAU DELTA x 330 Gr",
    "Salsa Chimichurri CASALTA x 335 Gr",
    "Aderezo Chimichurri TAU DELTA x 340 Gr",
    "Aderezo Big Tau TAU DELTA x 330 Gr",
    "Salsa Barbacoa CASALTA x 335 Gr",
    "Aderezo Barbacoa TAU DELTA x 340 Gr",
    "Aderezo Cheddar TAU DELTA x 330 Gr",
    "Aderezo Coleslaw TAU DELTA x 310 Gr",
    "Aderezo Ranch TAU DELTA x 330 Gr",
    "Aderezo Teriyaki TAU DELTA x 330 Gr",
    "Aderezo Ranch TAU DELTA X 0,900 Kg - Doy Pack",
    "Aderezo Ranch TAU DELTA X 3 Kg",
    "Harina Morixe 000 x 1 Kg ((( pack x 10 u )))",
    "Harina Favorita 000 x 1 Kg ((( pack x 15 u )))",
    "Harina Cañuelas 000 - Bolsa de 25 Kg.",
    "Harina Sarita 000 - Bolsa de 25 Kg.",
    "Harina Chacabuco 000 - Bolsa de 25 Kg.",
    "Harina Central Norte 000 - Bolsa de 25 Kg.",
    "Harina Morixe 0000 x 1 Kg ((( pack x 10 u )))",
    "Harina Favorita 0000 x 1 Kg ((( pack x 15 u )))",
    "Harina Cañuelas 0000 - Bolsa de 25 Kg.",
    "Harina Sarita 0000 - Bolsa de 25 Kg.",
    "Harina Chacabuco 0000 - Bolsa de 25 Kg.",
    "Harina Central Norte 0000 - Bolsa de 25 Kg.",
    "Harina Morixe Leudante x 1 Kg ((( pack x 10 u )))",
    "Harina BlancaFlor Leudante x 1 Kg ((( pack x 15 u )))",
    "Semolin Sarita - Bolsa de 25 Kg.",
    "Semolin Cañuelas - Bolsa de 25 Kg.",
    "Semolin Chacabuco - Bolsa de 25 Kg.",
    "Semolin Central Norte - Bolsa de 25 Kg.",
    "Faina - Fainalind - Bolsa de 10 Kg.",
    "Harina de Salvado de Trigo - GRANEL - Precio x Kilo",
    "Harina de Salvado de Trigo - Bolsa de 1 Kg - Fraccionada",
    "Harina Integral - GRANEL - Precio x Kilo",
    "Harina Integral - Bolsa de 1 Kg - Fraccionada",
    "Harina de Arroz mochi pulido - GRANEL - Precio x Kilo",
    "Harina de Arroz mochi pulido - Bolsa de 1 Kg - Fraccionada",
    "Harina de Arroz largo fino integral - GRANEL - Precio x Kilo",
    "Harina de Arroz largo fino integral - Bolsa de 1 Kg - Fraccionada",
    "Levadura - Calsa - Paquete 500 Grs.",
    "Maizena x 1,1 kg",
    "Maizena x 2 kg",
    "Maizena x 15kg",
    "Almidón de Maiz x 10 Kg - Buffalo (034010)",
    "Almidón de Maiz - GRANEL - Precio x Kilo",
    "Almidón de Maiz - Bolsa 1 Kg Fraccionada",
    "Fécula de Mandioca - GRANEL - Precio x Kilo",
    "Fécula de Mandioca - Bolsa 1 Kg Fraccionada",
    "Pan Rallado x 5 Kg - Morixe",
    "Pan Rallado x 5 Kg - Preferido",
    "Pan Rallado x 1 Kg - Preferido",
    "Pan Rallado x 1 Kg - Morixe",
    "Rebozador x 5 Kg - Morixe",
    "Rebozador x 5 Kg - Preferido",
    "Rebozador x 1 Kg - Preferido",
    "Panko Naranja x 10 Kg - Takumi",
    "Panko Blanco x 10 Kg - Takumi",
    "Fideos Tallarines - Don Vicente - Paquete 500 Gr.",
    "Fideos Caseritos - Don Vicente - Paquete 500 Gr.",
    "Fideos Fettuccini - Don Vicente - Paquete 500 Gr.",
    "Fideos Tallarines - Matarazzo - Paquete 500 Gr.",
    "Fideos Tallarines - Lucchetti - Paquete 500 Gr.",
    "Fideos Tirabuzon - Lucchetti - Paquete 500 Gr.",
    "Fideos Tirabuzon - Matarazzo - Paquete 500 Gr.",
    "Fideos Tirabuzon \"LIBRE DE GLUTEN\" - Matarazzo - Paquete 500 Gr.",
    "Fideos Tirabuzon \" INTEGRAL \" - Matarazzo - Paquete 500 Gr.",
    "Fideos Tirabuzon 3 Vegetales - Matarazzo - Paquete 500 Gr.",
    "Fideos Mostachol - Matarazzo - Paquete 500 Gr.",
    "Fideos Spaghetti - Lucchetti - Paquete 500 Gr.",
    "Fideos Spaghetti - Matarazzo - Paquete 500 Gr.",
    "Fideos Spaghetti \"LIBRE DE GLUTEN HIERRO\"- Matarazzo - Paquete 500 Gr.",
    "Fideos Spaghetti \" INTEGRAL \"- Matarazzo - Paquete 500 Gr.",
    "Fideos Rina Spaghetti - Matarazzo - Paquete 500 Gr.",
    "Fideos Rina Fusilli - Matarazzo - Paquete 500 Gr.",
    "Fideos Rina Espinaca Spaghetti - Matarazzo - Paquete 500 Gr.",
    "Fideos Municione - Lucchetti - Paquete 500 Gr.",
    "Fideos Dedalitos - Matarazzo - Paquete 500 Gr.",
    "Fideos Coditos - Matarazzo - Paquete 500 Gr.",
    "Fideos Coditos - Lucchetti - Paquete 500 Gr.",
    "Fideos Moños - Lucchetti - Paquete 500 Gr.",
    "Fideos Penne Rig - Lucchetti - Paquete 500 Gr.",
    "Fideos Penne Rig - Matarazzo - Paquete 500 Gr.",
    "Fideos Penne Rig \"LIBRE DE GLUTEN HIERRO\"- Matarazzo - Paquete 500 Gr.",
    "Fideos Penne Rig 3 Vegetales - Matarazzo - Paquete 500 Gr.",
    "Fideos de Arroz Natural Fino x 300 Grs - Soy Arroz",
    "Knorr Sopa Quick Vegetal Balance (( pack x 24 cajas x 5 sobres c/u ))",
    "Caldo Carne Cubo \"KNORR\" x 950 Grs",
    "Caldo Verdura Cubo \"KNORR\" x 950 Grs",
    "Caldo Gallina Cubo \"KNORR\" x 950 Grs",
    "Caldo Carne Granulado \"KNORR\" X 650 Grs",
    "Caldo Gallina Granulado \"KNORR\" X 650 Grs",
    "Caldo Verdura Granulado \"KNORR\" X 650 Grs",
    "Caldo Verdura Granulado c/sal - GRANEL - Precio x Kilo",
    "Caldo Verdura Granulado c/sal - Bolsa 1 Kilo Fraccionada",
    "Caldo Gallina Granulado c/sal - GRANEL - Precio x Kilo",
    "Caldo Gallina Granulado c/sal - Bolsa 1 Kilo Fraccionada",
    "Caldo Carne Granulado c/sal - GRANEL - Precio x Kilo",
    "Caldo Carne Granulado c/sal - Bolsa 1 Kilo Fraccionada",
    "Sal Dietetica x 90 g - GENSER",
    "Sal Fina - Caja x 1000 Sobres de 0,5 Grs - INYSA",
    "Sal Fina - Caja x 1000 Sobres de 0,5 Grs - DOS ANCLAS",
    "Sal Fina - Caja x 1000 Sobres de 0,5 Grs - ABEDUL",
    "Sal Fina - Bolsa 5 Kg. - Dos Anclas",
    "Sal Fina - Bolsa 25 Kg. - Recasal",
    "Sal Fina - Bolsa 25 Kg. \"LA PAMPA\" - Dos Anclas",
    "Sal Fina - Paquete 500 g. - Dos Anclas",
    "Sal Entrefina - Bolsa 25 Kg - Dos Anclas",
    "Sal Gruesa - Bolsa 25 Kg - Dos Anclas",
    "Sal Gruesa - Paquete 500 g. - Dos Anclas",
    "Sal Gruesa - Paquete 500 g. - Celusal",
    "Azucar - Caja de 800 Sobres - INYSA -",
    "Azucar Seleccion - LEDESMA - Caja 1000 Sobres x 5 Grs",
    "Azucar Seleccion - LEDESMA - Caja 1500 Sobres x 5 Grs",
    "Azucar Sweetella x 1 Kg (( pack x 10 unid ))",
    "Azucar x 1 Kg - LEDESMA (( pack x 10 unid ))",
    "Azucar Sweetella - Bolson 25 KG",
    "Azucar común tipo 'a' LEDESMA - Bolson 25 KG",
    "Azucar Impalpable - GRANEL - Precio x Kilo",
    "Azucar Impalpable - Bolsa 1 Kg Fraccionada",
    "Azucar Mascabo - Ledesma GRANEL - Precio x Kilo",
    "Azucar Mascabo - Bolsa 1 Kg Fraccionada",
    "Azucar Rubia - GRANEL - Precio x Kilo",
    "Azucar Rubia - Bolsa 1 Kg Fraccionada",
    "Azucar Negra - GRANEL - Precio x Kilo",
    "Azucar Negra - Bolsa 1 Kg Fraccionada",
    "Endulzante sucralosa - LEDESMA - Caja 400 Sobres x 0,8 Grs",
    "Endulzante STEVIA - LEDESMA - Caja 396 Sobres x 0,8 Grs",
    "Edulcorante - ABEDUL - Caja x 400 Sobres x 0,8 Grs",
    "Edulcorante - Caja x 400 Sobres - INYSA",
    "Edulcorante Liquido x 200 ml - Hileret Stevia ((pack x 9 unid))",
    "Extracto de Malta x 5 Kg - Hudson",
    "Citric Naranja - Bidon x 5 Lts",
    "CEPITA 20 % Naranja x 1 Lt (( caja x 8 unid ))",
    "BAGGIO Fresh Naranja x 200 ml (( caja x 18 unid ))",
    "BAGGIO Fresh Manzana x 200 ml (( caja x 18 unid ))",
    "BAGGIO Fresh Multifruta x 200 ml (( caja x 18 unid ))",
    "BAGGIO Fresh Durazno x 200 ml (( caja x 18 unid ))",
    "BAGGIO Pronto Naranja x 1 Lt (( caja x 8 unid ))",
    "Jugo base soja ADES - Sabor Natural x 1 Lt (( caja x 8 unid ))",
    "Licor de Chocolate x 700 ml - CUSENIER (( caja x 6 unid ))",
    "Licor de Chocolate x 700 ml - CUSENIER",
    "Vino Latitud 33 Malbec x 750 ml (caja x 6 u)",
    "Vino Latitud 33 Rose x 750 ml (caja x 6 u)",
    "Vino Latitud 33 Chardonnay x 750 ml (caja x 6 u)",
    "Vino Latitud 33 Cabernet Sauvignon x 750 ml (caja x 6 u)",
    "Vino Altos del Plata Cabernet Sauvignon x 750 ml (caja x 6 u)",
    "Vino Altos del Plata Malbec x 750 ml (caja x 6 u)",
    "Vino Terrazas de los Andes Cabernet Franc x 750 ml (caja x 6 u)",
    "Vino Terrazas de los Andes Reserva Malbec x 750 ml (caja x 6 u)",
    "Vino Terrazas de los Andres Reserva Malbec Rose x 750 ml (caja x 6 u)",
    "Vino tinto x 1 Lt - UVITA (( caja x 12 unid ))",
    "Vino blanco x 1 Lt - UVITA (( caja x 12 unid ))",
    "Arroz Yamani pulido y abrill - GRANEL - Precio x Kilo",
    "Arroz Yamani pulido y abrill - Bolsa de 1 Kg Fraccionada - JUMBALAY",
    "Arroz Yamani INTEGRAL - GRANEL - Precio x Kilo",
    "Arroz Yamani INTEGRAL - Bolsa de 5 Kg Fraccionada - JUMBALAY",
    "Arroz Yamani INTEGRAL - Bolsa de 1 Kg Fraccionada - JUMBALAY",
    "Arroz tipo Koshihikari p/Sushi - GRANEL - Precio x Kilo",
    "Arroz tipo Koshihikari p/Sushi - Bolsa de 1 Kg Fraccionada - JUMBALAY",
    "Arroz Largo Ancho Fortuna \"Doble Carolina\" - GRANEL",
    "Arroz Largo Ancho Fortuna \"Doble Carolina\" - Bolsa de 1 Kg Fraccionada - Precio x Kilo",
    "Arroz Largo Fino Integral - GRANEL - Precio x Kilo",
    "Arroz Largo Fino Integral - Bolsa de 1 Kg Fraccionada - Precio x Kilo",
    "Arroz Carnaroli - GRANEL - Precio x Kilo",
    "Arroz Carnaroli - Bolsa de 1 Kg Fraccionada - JUMBALAY",
    "Arroz Negro - GRANEL - Precio x Kilo",
    "Arroz Negro - Bolsa de 5 Kg Fraccionada - JUMBALAY",
    "Arroz Negro - Bolsa de 1 Kg Fraccionada - JUMBALAY",
    "Arroz Largo Fino - Lucchetti - x 1 Kg",
    "Arroz Parboil - Lucchetti - Bolsa 5 Kg",
    "Arroz Parboil - Gallo Oro - Bolsa 5 Kg",
    "Arroz Parboil - Don Marcos - Bolsa 5 Kg",
    "Arroz Carnaroli Gallo Oro - Bolsa 5 Kg",
    "Arroz Parboil - Don Marcos x 1 Kg",
    "Arroz Lucchetti Parboil x 1 Kg",
    "Arroz Gallo Oro Parboil x 1 Kg",
    "Garbanzos - GRANEL - Precio x Kilo",
    "Garbanzos - Bolsa de 1 Kg - Fraccionada",
    "Arvejas enteras - GRANEL - Precio x Kilo",
    "Arvejas enteras - Bolsa de 1 Kg - Fraccionada",
    "Arvejas partidas - GRANEL - Precio x Kilo",
    "Arvejas partidas - Bolsa de 1 Kg - Fraccionada",
    "Lentejas - GRANEL - Precio x Kilo",
    "Lentejas - Bolsa de 5 Kg - Fraccionada",
    "Lentejas - Bolsa de 1 Kg - Fraccionada",
    "Lentejon - GRANEL - Precio x Kilo",
    "Lentejon - Bolsa de 5 Kg - Fraccionada",
    "Lentejon - Bolsa de 1 Kg - Fraccionada",
    "Maíz Pisingallo - GRANEL - Precio x Kilo",
    "Maíz Pisingallo - Bolsa de 1 Kg - Fraccionada",
    "Maiz Pisado Blanco - GRANEL - Precio x Kilo",
    "Maiz Pisado Blanco - Bolsa de 1 Kg - Fraccionada",
    "Porotos Aduki - GRANEL - Precio x Kilo",
    "Porotos Aduki - Bolsa de 1 Kg - Fraccionada",
    "Porotos Manteca - GRANEL - Precio x Kilo",
    "Porotos Manteca - Bolsa de 1 Kg - Fraccionada",
    "Porotos Mung - GRANEL - Precio x Kilo",
    "Porotos Mung - Bolsa de 1 Kg - Fraccionada",
    "Porotos Negros - GRANEL - Precio x Kilo",
    "Porotos Negros - Bolsa de 1 Kg - Fraccionada",
    "Porotos Alubia - GRANEL - Precio x Kilo",
    "Porotos Alubia - Bolsa de 1 Kg - Fraccionada",
    "Porotos Colorados - GRANEL - Precio x Kilo",
    "Porotos Colorados - Bolsa de 1 Kg - Fraccionada",
    "Porotos Pallares - GRANEL - Precio x Kilo",
    "Porotos Pallares - Bolsa de 1 Kg - Fraccionada",
    "Cebada Perlada - GRANEL - Precio x Kilo",
    "Cebada Perlada - Bolsa de 1 Kg - Fraccionada",
    "Mix de Semillas (ses. integral - ses. negro - lino - chia - girasol) - Bolsa de 1 Kg",
    "Semillas Sesamo Blanco - GRANEL - Precio x Kilo",
    "Semillas Sesamo Blanco - Bolsa de 1 Kg - Fraccionada",
    "Semillas Sesamo Blanco - Bolsa de 0,500 Kg - Fraccionada",
    "Semillas Sesamo Integral - GRANEL - Precio x Kilo",
    "Semillas Sesamo Integral - Bolsa de 1 Kg - Fraccionada",
    "Semillas Sesamo Negro - GRANEL - Precio x Kilo",
    "Semillas Sesamo Negro - Bolsa de 1 Kg - Fraccionada",
    "Semillas De Zapallo - GRANEL - Precio x Kilo",
    "Semillas De Zapallo - Bolsa de 1 Kg - Fraccionada",
    "Semillas de Amapola - GRANEL - Precio x Kilo",
    "Semillas de Amapola - Bolsa de 1 Kg - Fraccionada",
    "Semillas De Lino - GRANEL - Precio x Kilo",
    "Semillas De Lino - Bolsa de 1 Kg - Fraccionada",
    "Semillas de Amaranto - GRANEL - Precio x Kilo",
    "Semillas de Amaranto - Bolsa de 1 Kg - Fraccionada",
    "Semillas de Girasol Peladas - GRANEL - Precio x Kilo",
    "Semillas de Girasol Peladas - Bolsa de 1 Kg - Fraccionada",
    "Semillas De Quinoa - GRANEL - Precio x Kilo",
    "Semillas De Quinoa - Bolsa de 1 Kg - Fraccionada",
    "Semillas De Quinoa Roja - GRANEL - Precio x Kilo",
    "Semillas De Quinoa Roja - Bolsa de 1 Kg - Fraccionada",
    "Semillas De Chia - GRANEL - Precio x Kilo",
    "Semillas De Chia - Bolsa de 1 Kg - Fraccionada",
    "Nueces Mariposa Chandler Extra Light - GRANEL - Precio x Kilo",
    "Nueces Mariposa Chandler Extra Light - Bolsa de 1 Kg - Fraccionada",
    "Nueces Mariposa Chandler Ambar Light - GRANEL - Precio x Kilo",
    "Nueces Mariposa Chandler Ambar Light - Bolsa de 1 Kg - Fraccionada",
    "Nueces Mariposa Chandler Ambar - GRANEL - Precio x Kilo",
    "Nueces Mariposa Chandler Ambar - Bolsa de 1 Kg - Fraccionada",
    "Nueces Cuartillos Chandler Extra Light - GRANEL - Precio x Kilo",
    "Nueces Cuartillos Chandler - Extra Light - Bolsa de 1 Kg - Fraccionada",
    "Nueces Cuartos Chandler Extra Light - GRANEL - Precio x Kilo",
    "Nueces Cuartos Chandler - Extra Light - Bolsa de 1 Kg - Fraccionada",
    "Nueces Cuartos Ambar Light - GRANEL - Precio x Kilo",
    "Nueces Cuartos Ambar Light - Bolsa de 1 Kg - Fraccionada",
    "Nueces Cuartos Ambar - GRANEL - Precio x Kilo",
    "Nueces Cuartos Ambar - Bolsa de 1 Kg - Fraccionada",
    "Nueces C/ Cascara Chandler 34-36 - GRANEL - Precio x Kilo",
    "Nueces con Cascara - Chandler 34-36 - Bolsa de 1 Kg - Fraccionada",
    "Nueces Pecan Peladas - GRANEL - Precio x Kilo",
    "Nueces Pecan Peladas - Bolsa de 1 Kg - Fraccionada",
    "Almendras NonPareil 4 (NP4) - GRANEL - Precio x Kilo",
    "Almendras NonPareil 4 (NP4) - Bolsa de 1 Kg - Fraccionada",
    "Almendras Guara 4 - GRANEL - Precio x Kilo",
    "Almendras Guara 4 - Bolsa de 1 Kg - Fraccionada",
    "Almendras Partida - GRANEL - Precio x Kilo",
    "Almendras Partida - Bolsa de 1 Kg - Fraccionada",
    "Almendras Ramillada - GRANEL - Precio x Kilo",
    "Almendras Ramillada - Bolsa de 1 Kg - Fraccionada",
    "Harina de Algarroba - GRANEL - Precio x Kilo",
    "Harina de Algarroba - Bolsa de 1 Kg - Fraccionada",
    "Harina de Almendras - GRANEL - Precio x Kilo",
    "Harina de Almendras - Bolsa de 1 Kg - Fraccionada",
    "Harina de Almendras s/PIEL - GRANEL - Precio x Kilo",
    "Harina de Almendras s/PIEL - Bolsa de 1 Kg - Fraccionada",
    "Castañas Cayu W4 - GRANEL - Precio x Kilo",
    "Castañas Cayu W4 - Bolsa de 1 Kg - Fraccionada",
    "Castañas Tost Y Sal - GRANEL - Precio x Kilo",
    "Castañas Tostadas y Saladas - Bolsa de 1 Kg - Fraccionada",
    "Avellanas Peladas - GRANEL - Precio x Kilo",
    "Avellanas Peladas - Bolsa de 1 Kg - Fraccionada",
    "Pistachos Enteros Natural Pelados - GRANEL - Precio x Kilo",
    "Pistachos Enteros Natural Pelados - Bolsa de 1 Kg - Fraccionada",
    "Pistachos Pelados Trozo - GRANEL - Precio x Kilo",
    "Pistachos Pelados Trozo - Bolsa de 1 Kg - Fraccionada",
    "Pistachos Tost Y Sal - GRANEL - Precio x Kilo",
    "Pistachos Tostados y Salados - Bolsa de 1 Kg - Fraccionada",
    "Mix De Fruta Tradicional - Bolsa de 1 Kg - Fraccionada",
    "Mix De Fruta Tradicional ECONOMICO - Bolsa de 1 Kg - Fraccionada",
    "Mix De Fruta con Bananas - Bolsa de 1 Kg - Fraccionada",
    "Mix De Fruta con Bananas ECONOMICO - Bolsa de 1 Kg - Fraccionada",
    "Mix De Fruta Tropical - Bolsa de 1 Kg - Fraccionada",
    "Mix De Frutas Secas Europeo ((Sin Pasas)) - Bolsa de 1 Kg - Fraccionada",
    "Mani Repelado Salado - GRANEL - Precio x Kilo",
    "Mani Repelado Salado - Bolsa de 1 Kg - Fraccionada",
    "Mani Repelado Tostado ((Sin Sal)) - GRANEL - Precio x Kilo",
    "Mani Repelado Tostado ((Sin Sal)) - Bolsa de 1 Kg - Fraccionada",
    "Mani C/cascara - GRANEL - Precio x Kilo",
    "Mani con Cascara - Bolsa de 1 Kg - Fraccionada",
    "Mani Japones Clasico - GRANEL - Precio x Kilo",
    "Mani Japones Clasico - Bolsa de 1 Kg - Fraccionada",
    "Granola Crocante - GRANIX - GRANEL x 3 Kg",
    "Granola Crocante - GRANIX - Bolsa de 1 kg - Fraccionada",
    "Granola Crocante Pasas y Almendras - GRANIX - GRANEL x 3 Kg",
    "Granola Crocante Pasas y Almendras - GRANIX - Bolsa de 1 kg - Fraccionada",
    "Granola Crocante Frutos Rojos - GRANIX - GRANEL x 3 Kg",
    "Granola Crocante Frutos Rojos - GRANIX - Bolsa de 1 kg - Fraccionada",
    "Bocaditos rellenos de Frutilla - GRANIX - x 4 Kg",
    "Bocaditos rellenos de Frutilla - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Bocaditos rellenos de Limon - GRANIX - x 4 Kg",
    "Bocaditos rellenos de Limon - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Bocaditos rellenos de Chocolate Blanco - GRANIX - x 4 Kg",
    "Bocaditos rellenos de Chocolate Blanco - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Copos de Maiz - GRANIX - x 3 Kg",
    "Copos de Maiz - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Copos de Maiz azucarados - GRANIX - x 3,4 Kg",
    "Copos de Maiz Azucarados - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Aritos Frutales - GRANIX - x 2,5 Kg",
    "Aritos Frutales - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Bolitas de Chocolate - GRANIX - x 3 Kg",
    "Bolitas de Chocolate - GRANIX - Bolsa de 1 Kg - Fraccionada",
    "Avena Arrollada Instantanea - GRANEL - Precio x Kilo",
    "Avena Arrollada Instantanea - Bolsa de 1 Kg - Fraccionada",
    "Avena Arrollada Gruesa - GRANEL - Precio x Kilo",
    "Avena Arrollada Gruesa - Bolsa de 1 Kg - Fraccionada",
    "Avena Arrollada Media - GRANEL - Precio x Kilo",
    "Avena Arrollada Media - Bolsa de 1 Kg - Fraccionada",
    "Pasas De Uva Jumbo - GRANEL - Precio x Kilo",
    "Pasas De Uva Jumbo - Bolsa de 1 Kg - Fraccionada",
    "Pasas De Uva Sultaninas - GRANEL - Precio x Kilo",
    "Pasas De Uva Sultaninas - Bolsa de 1 Kg - Fraccionada",
    "Pasas De Uva Rubias - GRANEL - Precio x Kilo",
    "Pasas De Uva Rubias - Bolsa de 1 Kg - Fraccionada",
    "Ciruelas Bombon 132/154 - GRANEL - Precio x Kilo",
    "Ciruelas Bombon 132/154 - Bolsa de 1 Kg - Fraccionada",
    "Duraznos Medianos - GRANEL - Precio x Kilo",
    "Duraznos Medianos - Bolsa de 1 Kg - Fraccionada",
    "Higos Negros - GRANEL - Precio x Kilo",
    "Higos Negros - Bolsa de 1 Kg - Fraccionada",
    "Pera Williams Mediana - GRANEL - Precio x Kilo",
    "Pera Williams Mediana - Bolsa de 1 Kg - Fraccionada",
    "Datiles De Egipto C/carozo - GRANEL - Precio x Kilo",
    "Datiles De Egipto C/carozo - Bolsa de 1 Kg - Fraccionada",
    "Banana Chips - GRANEL - Precio x Kilo",
    "Banana Chips - Bolsa de 1 Kg - Fraccionada",
    "Manzana En Cubos - GRANEL - Precio x Kilo",
    "Manzana En Cubos - Bolsa de 1 Kg - Fraccionada",
    "Arandanos Rojos Deshidratados Rebanados - GRANEL - Precio x Kilo",
    "Arandanos Rojos Deshidratados Rebanados - Bolsa de 1 Kg - Fraccionada",
    "Tomates Secos Peritas x Mitades - GRANEL - Precio x Kilo",
    "Tomates Secos Peritas x Mitades - Bolsa 1 Kg - Fraccionada",
    "Tomates Secos Peritas x Mitades (OFERTA) - GRANEL - Precio x Kilo",
    "Tomates Secos Peritas x Mitades ((OFERTA)) - Bolsa 1 Kg - Fraccionada",
    "Fruta Glaseada - GRANEL - Precio x Kilo",
    "Fruta Glaseada - Bolsa 1 Kg - Fraccionada",
    "Fruta Nevada - ((( Caja de 5 Kg )))",
    "Fruta Escurrida - GRANEL - Precio x Kilo",
    "Fruta Escurrida - Bolsa 1 Kg - Fraccionada",
    "Fruta Escurrida especial - GRANEL - Precio x Kilo",
    "Fruta Escurrida especial - Bolsa 1 Kg - Fraccionada",
    "Higos Glaseados - ((( Caja de 2 Kg )))",
    "Cascara De Naranja Glaseada - ((( Caja de 2 Kg )))",
    "Cascara Naranja glaseada en tiras - ((( Caja de 2 Kg )))",
    "Limon Glaseado En Tiras - ((( Caja de 2 Kg )))",
    "Cacao Amargo en Polvo Alcalino x Kg",
    "Cacao Amargo en Polvo - Bolsa x 1 Kg",
    "Cacao Dulce en Polvo - Bolsa x 1 Kg",
    "Almendras C/ Chocolate Negro X 1kg",
    "Drops Gotas de Chocolate Semi Amargo AGUILA \"COD.9641\" ((( CAJA DE 10 KG )))",
    "Drops Gotas de Chocolate Blanco AGUILA \"COD.9323\" ((( CAJA DE 5 KG )))",
    "Pasas De Uva C/ Chocolate X 1kg",
    "Mani C /chocolate X1kg",
    "Garrapiñada de Mani - GRANEL - Precio x Kg",
    "Garrapiñada de Mani - Bolsa x 1 Kg - Fraccionada",
    "Lentejas de Chocolate ROCKLETS - Bolsa x 1kg - Fraccionada",
    "Lentejas de Chocolate ROCKLETS \"COD.9780\" - (((CAJA X 10 KG)))",
    "Chocolate NEGRO Taza AGUILA - (( Display 24 u x 14 Gr ))",
    "Chocolate NEGRO Taza AGUILA \"COD.9985\" - ((( CAJA DE 5 KG )))",
    "Chocolate BLANCO Taza AGUILA \"COD.9979\" - ((( CAJA DE 5 KG )))",
    "Bombones de Fruta - Bolsa 1 Kg - Fraccionada",
    "Frutillas c/ Cabo - Caja x 1 Kg",
    "Nachos K-Mexicano - ANTOJITOS ((caja 15 u x 250 Grs))",
    "Mecano - Bonafide *(caja x 24 u x 19 Gr)*",
    "Mecano chocolate Blanco - Bonafide *(caja x 24 u x 19 Gr)*",
    "Moneda Capitan Morgan - Bonafide *(bolsa x 500 Grs)*",
    "Nugaton leche (negro) - Bonafide *(caja x 24 u x 27 Gr)*",
    "Nugaton blanco - Bonafide *(caja x 24 u x 27 Gr)*",
    "Galletitas Oreo x 354 Grs *(caja x 12 pack x 3 unid)*",
    "Galletitas Chocolinas x 170 Grs *(caja x 40 unid)*",
    "Galletitas Lincoln x 153 Grs *(caja x 60 unid)*",
    "Galletitas Sonrisas 108 Grs *(caja 12 pack x 3 unid)*",
    "Galletitas Merengadas x 88 Grs *(caja 12 pack x 3 unid)*",
    "Galletitas Vocacion clasica x 384 Grs *(caja x 36 unidades)*",
    "Galletitas Coquitas x 260 Grs *(caja x 25 unidades)*",
    "Vainillas Pozo x 444 Grs *(caja x 8 unidades)*",
    "Pionono dulce - Bonafide *(caja x 25 u x 180 Gr)*",
    "Semola Vitina Clasica x 500 Grs *(pack x 6 unidades)*",
    "Barquillos x 150 Grs - Madina",
    "Polenta x 500 Grs - Presto Pronta",
    "Arepas x 1000 Grs - Presto Pronta",
    "Jugo Clight sabor Limonada dulce x 140 Grs - *(Caja 20 sobres x 7 grs)*",
    "Jugo Clight sabor Pomelo x 140 Grs - *(Caja 20 sobres x 7 grs)*",
    "Jugo Clight sabor Naranja x 140 Grs - *(Caja 20 sobres x 7 grs)*",
    "Jugo Tang sabor Limonada dulce x 300 Grs - *(Caja 20 sobres x 15 grs)*",
    "Jugo Tang sabor Manzana x 300 Grs - *(Caja 20 sobres x 15 grs)*",
    "Jugo Tang sabor Naranja x 300 Grs - *(Caja 20 sobres x 15 grs)*",
    "Cacao Nesquik Original x 2 kg",
    "Café instantaneo Tradicional DP x 100 Grs - NESCAFE ((caja x 8 unid))",
    "CAPSULAS Dolce Gusto Espresso x 96 Gr (caja x 16 unid)",
    "CAPSULAS Dolce Gusto Café Au Lait x 96 Gr (caja x 16 unid)",
    "Cafe Sensaciones INTENSO x 1 Kg - Bonafide *(caja x 6 u)*",
    "Cafe Sensaciones en saquitos INTENSO - Bonafide *(caja x 18 u x 5 Gr)*",
    "Cafe Suave x 170 Gr - Arlistan *(pack x 12 u)*",
    "Mate Cocido NOBLEZA GAUCHA s/ensobrar (100 saq) *(pack x 5 cajas)*",
    "Te GREEN HILLS ensobrado (100 saq x 2 Gr.) *(Pack x 9 cajas)*",
    "Te GREEN HILLS ensobrado (100 saq x 2 Gr.)",
    "Te de Manzanilla - La Virginia (caja x 25 saquitos)",
    "Te de Tilo - La Virginia (caja x 25 saquitos)",
    "Yerba Mate Cruz de Malta \"Tradicional\" - x 500 grs *(pack x 10 u)*",
    "Yerba Mate Cruz de Malta \"Tradicional\" - x 1 Kg *(pack x 6 u)*",
    "Yerba Mate Cruz de Malta \"Suave\" Seleccion Especial - x 1 Kg *(pack x 6 u)*",
    "Bialcohol 70º Desinfeccion - Bidon x 5 Lts",
    "Bialcohol 96º Alimenticio - Bidon x 5 Lts",
    "Mix Cake Vainilla x 3 Kg - Keuken",
    "Baño de reposteria Blanco x 20 Kg - Alpino",
    "Crema pastelera x 3 Kg - Calsa",
    "Caramelo Líquido - BACIGALUPO - Botella x 1250 g",
    "Esencia de Vainilla - Mayana - Bidón x 5 Lts",
    "Esencia de Vainilla - Mayana - Bidón x 1 Lt",
    "Bizcochuelo de Vainilla x 5 Kgs - Orloc",
    "Bizcochuelo de Chocolate x 5 Kgs - Orloc",
    "Bizcochuelo de Naranja x 5 Kgs - Orloc",
    "Flan Chocolate x 1 kg - Orloc",
    "Flan Chocolate x 5 kgs - Orloc",
    "Flan Dulce de Leche x 5 kgs - Orloc",
    "Flan Vainilla x 1 kg - Orloc",
    "Flan Vainilla x 5 kgs - Orloc",
    "Flan Vainilla Light x 1 kg - Ravana",
    "Gelatina Anana x 5 Kg - Orloc",
    "Gelatina Cereza x 1 Kg - Orloc",
    "Gelatina Cereza x 5 Kgs - Orloc",
    "Gelatina Durazno x 1 Kg - Orloc",
    "Gelatina Durazno x 5 Kg - Orloc",
    "Gelatina Frambuesa x 1 Kg - Orloc",
    "Gelatina Frambuesa x 5 Kgs - Orloc",
    "Gelatina Frutilla x 1 Kg - Orloc",
    "Gelatina Frutilla x 5 Kgs - Orloc",
    "Gelatina Manzana x 1 Kg - Orloc",
    "Gelatina Manzan x 5 Kgs - Orloc",
    "Gelatina sin sabor x 1 Kg - Mayana",
    "Gelatina DIET Cereza x 1 Kg - Orloc",
    "Gelatina DIET Frutilla x 1 Kg - Orloc",
    "Mousse Chocolate x 5 Kgs - Orloc",
    "Mousse de Chocolate x 3 Kg - Keuken",
    "Carte Dor BROWNIE y VOLCAN x 1 Kg",
    "Carte Dor MOUSSE DE CHOCOLATE x 1 Kg",
    "Carte Dor TIRAMISU x 1 Kg",
    "Carte Dor BAS PASTELERIA x 1 Kg",
    "Postre Chocolate x 1 kg - Orloc",
    "Postre Vainilla x 1 kg - Orloc",
    "Nucrem - Balde x 5,5 Kg",
    "Charlotte tradicional x 960 Grs - Stapler",
    "Pulpa de Frutilla p/cocteleria x 880 Grs - Stapler",
    "Ferrero NUTELLA - Frasco x 350 Grs",
    "Ferrero NUTELLA - Balde x 3 Kg",
    "Aji molido Extra - Bolsa 1 Kg - Fraccionada",
    "Aji Molido \"B\" - Bolsa 1 Kg - Fraccionada",
    "Ají Cayena Rojo - Bolsa 1 Kg - Fraccionada",
    "Ají Cayena Amarillo - Bolsa 1 Kg - Fraccionada",
    "Azafrán Económico Nacional (40 capsulas)",
    "Canela Molida Extra - Bolsa 1 Kg - Fraccionada",
    "Canela en Rama H2 - Bolsa 1 Kg - Fraccionada",
    "Cardamomo en grano - Bolsa 1 Kg - Fraccionada",
    "Coco Rallado - LOW FAT - Bolsa 1 Kg - Fraccionada",
    "Coco Rallado - HIGHT FAT - Bolsa 1 Kg - Fraccionada",
    "Clavo de olor molido (pedunculo) - Bolsa 1 Kg - Fraccionada",
    "Comino Molido Extra Nacional - Bolsa 1 Kg - Fraccionada",
    "Comino Molido \"B\" - Bolsa 1 Kg - Fraccionada",
    "Coriandro Molido - Bolsa 1 Kg - Fraccionada",
    "Coriandro Grano - Bolsa 1 Kg - Fraccionada",
    "Cous Cous - (( Caja de 500 Grs )) - origen Francia",
    "Cous Cous - Bolsa 1 Kg - Fraccionada",
    "Curcuma Molida Extra - Bolsa 1 Kg - Fraccionada",
    "Curcuma \"B\" - Bolsa 1 Kg - Fraccionada",
    "Eneldo - Bolsa 1 Kg - Fraccionada",
    "Estragón - Bolsa 1 Kg - Fraccionada",
    "Hinojo Grano - Bolsa 1 Kg - Fraccionada",
    "Hinojo Molido - Bolsa 1 Kg - Fraccionada",
    "Jengibre Molido - Bolsa 1 Kg - Fraccionada",
    "Kúmel Molido - Bolsa 1 Kg - Fraccionada",
    "Kúmel Entero - Bolsa 1 Kg - Fraccionada",
    "Laurel en hojas Nacional - Bolsa 1 Kg - Fraccionada",
    "Mostaza Molida - Bolsa 1 Kg - Fraccionada",
    "Mostaza en Grano - Bolsa 1 Kg - Fraccionada",
    "Nuez moscada Grano - Bolsa 1 Kg - Fraccionada",
    "Nuez moscada molida Extra - Bolsa 1 Kg - Fraccionada",
    "Nuez Moscada Molida B - Bolsa 1 Kg - Fraccionada",
    "Orégano Extra - Bolsa 1 Kg - Fraccionada",
    "Orégano \"B\" - Bolsa 1 Kg - Fraccionada",
    "Páprika (pimentón picante) - Bolsa 1 Kg - Fraccionada",
    "Pimentón Extra - Bolsa 1 Kg - Fraccionada",
    "Pimentón \"B\" - Bolsa 1 Kg - Fraccionada",
    "Pimenton Ahumado - Bolsa 1 Kg - Fraccionada",
    "Pimienta Blanca en Grano - Bolsa 1 Kg - Fraccionada",
    "Pimienta Blanca Molida Brasil - Bolsa 1 Kg - Fraccionada",
    "Pimienta Blanca \" B\" - Bolsa 1 Kg - Fraccionada",
    "Pimienta Negra en Grano - Bolsa 1 Kg - Fraccionada",
    "Pimienta Negra Molida Brasil - Bolsa 1 Kg - Fraccionada",
    "Pimienta Negra \" B\" - Bolsa 1 Kg - Fraccionada",
    "Romero - Bolsa 1 Kg - Fraccionada",
    "Soja Texturizada Fina - GRANEL",
    "Soja Texturizada Fina - Bolsa 1 Kg - Fraccionada",
    "Trigo Burgol - GRANEL",
    "Trigo Burgol - Bolsa 1 Kg - Fraccionada",
    "Tomillo Cultivado - Bolsa 1 Kg - Fraccionada",
    "Ajo Granulado Nacional - Bolsa 1 Kg - Fraccionada",
    "Ajo polvo - Bolsa 1 Kg - Fraccionada",
    "Dientes de Ajo Negro *(caja x 10 u x 100 Grs c/u)*",
    "Albahaca deshidratada - Bolsa 1 Kg - Fraccionada",
    "Cebolla en escamas Kibbled - GRANEL - Precio x Kilo",
    "Cebolla en Escamas - Kibbled - Bolsa 1 Kg - Fraccionada",
    "Cebolla en Polvo - Bolsa 1 Kg - Fraccionada",
    "Hongo Secos (Boletus) Premiun - Bolsa 1 Kg - Fraccionada",
    "Perejil deshidratado-Premium - Bolsa 1 Kg - Fraccionada",
    "Perejil deshidratado B - Bolsa 1 Kg - Fraccionada",
    "Provenzal P2 c/ Ajo Chino - Bolsa 1 Kg - Fraccionada",
    "Provenzal Mezcla ST - Bolsa 1 Kg - Fraccionada",
    "Pure de Papas - GRANEL - Precio x Kilo",
    "Puré de Papas - Bolsa de 1 Kg - Fraccionada",
    "Sopa juliana - Bolsa 1 Kg - Fraccionada",
    "Condimento para Pizza \"B\" - Bolsa 1 Kg - Fraccionada",
    "Chimichurri \"B\" - Bolsa 1 Kg - Fraccionada",
    "Condimento p/arroz - Bolsa 1 Kg - Fraccionada",
    "Curry B - Bolsa 1 Kg - Fraccionada",
    "Huevo en Polvo - Bolsa 1 Kg - Fraccionada",
    "Polvo para Hornear - Bolsa 1 Kg - Fraccionada",
    "Bicarbonato de Sodio - Bolsa 1 Kg - Fraccionada",
    "Tapa p/empanadas rotisera x 13,5 cm - CRIOLLO x 60 unid ((2600 Grs.)) CON SEP",
    "Bebida a base de Almendras SIN AZUCAR - SILK (Caja x 12 unidades)",
    "Bebida a base de Almendras endulzada - SILK (Caja x 12 unidades)",
    "Bebida a base de Almendras con Chocolate - SILK (Caja x 12 unidades)",
    "Bebida a base de Almendras sabor Vainilla s/azucar - SILK (Caja x 12 unidades)",
    "Bebida a base de Coco SIN AZUCAR - SILK (Caja x 12 unidades)",
    "Bebida a base de Coco endulzada - SILK (Caja x 12 unidades)",
    "Leche de Almendras 100 % Vegetal - La Serenisima (Caja x 12 unidades)",
    "Leche de Almendras 100 % Vegetal SIN AZUCAR - La Serenisima (Caja x 12 unidades)",
    "Leche de Almendras BARISTA 100 % Vegetal SIN AZUCAR - La Serenisima (Caja x 12 unidades)",
    "Leche de Almendras Tratenfu Original (Caja x 8 unidades)",
    "Leche Entera Clasica Fort 3% x 1 LT - La Serenisima (pack x 6 unid)",
    "Leche Barista x 1 LT - La Serenisima (pack x 6 unid)",
    "Leche con Prebióticos x 1LT - La Serenisima (pack x 6 unid)",
    "Leche Protein x 1 LT - La Serenisima (pack x 6 unid)",
    "Leche Zero 0% Lactosa x 1 LT - La Serenisima (pack x 6 unid)",
    "Leche L.V. Entera x 1 LT - Yatasto (caja x 12 unid)",
    "Leche L.V. Entera Clasica x 1 LT - La Serenisima (caja x 12 unid)",
    "Leche L.V. Entera x 1 LT - Veronica (caja x 12 unid)",
    "Leche L.V. Parc. Descremada x 1 LT - La Serenisima (caja x 12 unid)",
    "Leche L.V. Parc. Descremada x 1 LT - Veronica (caja x 12 unid)",
    "Leche Condensada x 395 Gr - NESTLE (caja x 24 unid)",
    "Leche Condensada x 395 Gr - NESTLE",
    "Leche en Polvo Descremada x 5 Gr. - ABEDUL (( caja x 100 unid ))",
    "Leche en Polvo Entera - Bolson 25 Kg - Veronica",
    "Leche en Polvo Entera - Bolson 25 Kg - Molfino",
    "Leche en Polvo Descremada - Bolson 25 Kg - Veronica",
    "Leche en Polvo Zero 0% Lactosa x 400 Grs - La Serenisima",
    "Leche Chocolatada x 1 LT - CINDOR (pack x 12 unid)",
    "Leche Chocolatada Clásico x 1 LT - La Serenisima (pack x 12 unid)",
    "Leche Chocolatada x 200 ml - CINDOR (pack x 24 unid)",
    "Leche Chocolatada Clásico x 200 ml - La Serenisima (pack x 24 unid)",
    "Crema de Leche x 5lts Sachet - La Paulina - (36%)",
    "Crema de Leche x 5lts Balde - La Paulina - (36%)",
    "Crema de Leche x 4 lts - TONADITA",
    "Crema de Leche x 5lts Balde - MILKAUT - (44%)",
    "Crema de Leche \"Pastelera\" x 10 Lts Sachet - VACALIN - (44%)",
    "Crema de Leche x 5lts Sachet - MILKAUT - (39%)",
    "Crema para Batir Fort. con Vitaminas x 520 ml - La Serenísima (pack x 12 u)",
    "Dulce de Leche Heladero - VACALIN - Balde x 10 Kgs",
    "Dulce de Leche Familiar - Mayol x 10 kgs",
    "Dulce de Leche Original - VACALIN - Balde x 10 Kgs",
    "Dulce de Leche Original - VACALIN - Balde x 4 Kgs",
    "Dulce de Leche Repostero - Mayol x 10 kgs",
    "Dulce de Leche Repostero - VACALIN - Balde x 10 Kgs",
    "Dulce de Leche Repostero - VACALIN - Cuñete x 10 Kgs",
    "Dulce de Leche Repostero - VACALIN - Balde x 4 Kgs",
    "Dulce de Leche Familiar - Mayol x 1 Kg",
    "Dulce de Leche Original - VACALIN x 1 Kg",
    "Dulce de Leche Familiar - Mayol x 1/2 Kg",
    "Dulce de Leche Repostero - Mayol x 1 Kg",
    "Dulce de Leche Repostero - VACALIN x 1 Kg",
    "Dulce de Leche Colonial x 1 Kg - La Serenisima",
    "Manteca - TONADITA ((( Caja de 100 Unidades x 10 Grs )))",
    "Manteca - VERONICA ((( Caja de 144 Unidades x 10 Grs )))",
    "Manteca x 5 kg - Teodoro - Precio x Unidad",
    "Manteca x 5 kg - TONADITA - Precio x Unidad",
    "Manteca x 5 kg - LA PAULINA - Precio x Unidad",
    "Manteca x 5 kg - VACALIN - Precio x Unidad",
    "Manteca x 5 Kg \"calidad extra\" - EL VAQUERO - Precio x Unidad",
    "Manteca x 5 kg - MILKAUT - Precio x Unidad",
    "Manteca x 25 kg - LA PAULINA - Precio x Unidad",
    "Manteca x 25 kg - MILKAUT - Precio x Unidad",
    "Queso Brie - La Bohem - Precio x Kilo",
    "Queso Azul - LA PAULINA - Precio x Unidad",
    "Queso Azul - ALLOA - Precio x Kilo",
    "Queso Azul - CAMPO BIANCO - Precio x Kilo",
    "Queso Azul - LA QUESERA - Precio x Kilo",
    "Queso Cremoso - Barraza - Precio x Kilo",
    "Queso Cremoso - Don Manuel - Precio x Kilo",
    "Queso Cremoso - LA PAULINA - Precio x Kilo",
    "Queso Port Salut con Sal (SIN TACC) - VERONICA - Precio x Kilo",
    "Queso Cheddar Finlandia - Barra x 2 Kg",
    "Queso Cheddar en hebras x 1 Kg - LA PAULINA - Precio x Unidad",
    "Queso Cheddar barra p/fetear - LA PAULINA - Precio x Kg",
    "Queso Cheddar Barra de 192 Fetas x 2,37 Kg - MILKAUT - Precio x Unidad",
    "Queso Cheddar AMERICANO Barra de 168 Fetas x 2,01 Kg - TONADITA - Precio x Unid",
    "Queso Cheddar Pouch x 4 Kg - LA QUESERA - Precio x Unidad",
    "Queso Cheddar Pouch 3 Kg x - TONADITA - Precio x Unidad",
    "Queso Cheddar Pouch x 3,7 Kg - LA PAULINA - Precio x Unidad",
    "Queso Cheddar Pouch x 3,5 Kg - MILKAUT - Precio x Unidad",
    "Queso Cheddar Doy Pack x 1,5 Kg - MILKAUT - Precio x Unidad",
    "Queso Crema - Pouch x 4 Kg - LA PAULINA - Precio x Unidad",
    "Queso Crema - Pouch x 4 Kg - CASANCREM - Precio x Unidad",
    "Queso Crema x 3,6 Kg Balde - MILKAUT - Precio x Unidad",
    "Queso Crema \"Estilo Italiano\" - Pouch x 4 Kg - LA SERENISIMA Profesional - Precio x Unidad",
    "Queso Crematto x 3,5 Kg - MILKAUT - Precio x Unidad",
    "Queso Crema x 3 Kg - PATAGONIA TONADITA - Precio x Unidad",
    "Queso Crematto Doy Pack x 1,5 Kg - MILKAUT - Precio x Unidad",
    "Queso untable PATAGONIA - TONADITA (caja de 90 unidades x 20 g)",
    "Queso Finlandia Clasico - Manga x 2 kg",
    "Queso untable GRUYERE - TONADITA (caja de 12 unidades x 180 g)",
    "Queso Rallado x 3 Kg - La Quesera",
    "Queso Provolone Semi Estacionado en Hebras x 1000 Grs.",
    "Queso Rallado x 8 Gr - La Quesera (Display x 100 sobres)",
    "Muzzarella Barraza x 10 Kgs - Precio x Kilo",
    "Muzzarella x 10 kg \"Premium\" - DO PENSO - Precio x Kilo",
    "Muzzarella x 10 kg - DO PENSO - Precio x Kilo",
    "Muzzarella Barraza x 5 Kgs - Precio x Kilo",
    "Muzzarella DO PENSO x 5 Kgs (Cilindro) - Precio x Kilo",
    "Muzzarella Barraza - Cilindro 3 Kgs - Precio x Kilo",
    "Queso Mozzarella en Barra Tradicional - LA PAULINA - Precio x Kilo",
    "Queso Mozzarella en Barra p/fetear - LA PAULINA - Precio x Kilo",
    "Queso Danbo en Barra - LA PAULINA - Precio x Kilo",
    "Queso Prato en Barra - LA PAULINA - Precio x Kilo",
    "Queso Tybo en Barra - VERONICA - Precio x Kilo",
    "Queso Tybo en Barra - DON MANUEL - Precio x Kilo",
    "Queso Tybo en Barra - LA PAULINA - Precio x Kilo",
    "Queso Tybo (caja 12 paquetes x 8 fetas c/u) - LA PAULINA - Precio x caja",
    "Queso Tybo Ahumado en Barra - DON MANUEL - Precio x Kilo",
    "Mini Horma de Queso Gouda - DON MANUEL - (Precio x Unidad)",
    "Mini Horma de Queso Gouda Saborizado - DON MANUEL - (Precio x Unidad)",
    "Mini Horma de Queso Gouda Ahumado - DON MANUEL - (Precio x Unidad)",
    "Queso Holanda - DON MANUEL - Precio x Kilo",
    "Queso Pategras - DON MANUEL - Precio x Kilo",
    "Queso Pategras - LA PAULINA - Precio x Kilo",
    "Mini Horma de Queso Sardo - DON MANUEL - (Precio x Unidad)",
    "Mini Horma de Queso Sardo Ahumado - DON MANUEL - (Precio x Unidad)",
    "Mini Horma de Queso Holanda - DON MANUEL - (Precio x Unidad)",
    "Mini Horma de Queso Pategras - DON MANUEL - (Precio x Unidad)",
    "Queso Criollo - DON MANUEL - Precio x Kilo",
    "Queso Criollo Condimentado - DON MANUEL - Precio x Kilo",
    "Queso Criollo Ahumado - DON MANUEL - Precio x Kilo",
    "Queso Parmessano - EL VAQUERO - Precio x Kilo",
    "Queso Parmessano (1/2 horma al Vacio) - EL VAQUERO - Precio x Kilo",
    "Queso Provoleta - DON MANUEL - Precio x Kilo",
    "Queso Provoleta - VAQUERO - Precio x Kilo",
    "Queso Provoleta - NONNA PIA - Precio x Kilo",
    "Queso Provolone Fresco - DON MANUEL - Precio x Kilo",
    "Queso Provolone Semi Estacionado (1/2 Horma Envasada al Vacío) - Precio x Kilo",
    "Queso Reggianito - EL VAQUERO - Precio x Kilo",
    "Queso Reggianito (1/2 Horma al Vacio) - EL VAQUERO - Precio x Kilo",
    "Queso Reggianito - DON MANUEL - Precio x Kilo",
    "Queso Sardo Fresco - DON MANUEL - Precio x Kilo",
    "Queso Sardo Fresco - DON ALFONSO - Precio x Kilo",
    "Queso Sardo Fresco AHUMADO - DON MANUEL - Precio x Kilo",
    "Queso Sardo Semi Estacionado - DON MANUEL - Precio x Kilo",
    "Queso Sardo Semi Estacionado (1/2 Horma Envasada al Vacío) - Precio x Kilo",
    "Queso Sardo Estacionado - El Vaquero - Precio x Kilo",
    "Queso Sardo Estacionado (1/2 Horma al Vacio) - El Vaquero - Precio x Kilo",
    "Ricota - Don Manuel - Precio x Kilo",
    "Yogur Natural S/azucar Yogurisimo x 300 gr (bandeja x 12 unid)",
    "Yogur Natural S/azucar Yogurisimo x 300 gr",
    "Yogur c/cereales clasico x 159 gr- La Serenísima (bandeja x 12 unid)",
    "Yogur c/cereales descremado x 157 gr- La Serenísima (bandeja x 12 unid)",
    "Bondiola al vacio - CAMPO AUSTRAL - Precio x Kilo",
    "Fiambre Cocido de Cerdo Especial LARIO - Precio x Kilo",
    "Fiambre Cocido de Pata de Cerdo - Australia 1284 - Precio x Kilo",
    "Fiambre Cocido de Paleta de Cerdo - ORFEBRE La Octava - Precio x Kilo",
    "Jamon Cocido QUIRO MAS - Precio x Kilo",
    "Jamon Cocido - Scudetto - Precio x Kilo",
    "Jamon Cocido LARIO - Precio x Kilo",
    "Jamon Cocido - CAMPO AUSTRAL - Precio x Kilo",
    "Jamon Cocido (BARRA) - CAMPO AUSTRAL - Precio x Kilo",
    "Jamon Cocido Natural Cerdo Millenium - CAMPO AUSTRAL - Precio x Kilo",
    "Jamon Crudo \"RENDIDOR\" - CAMPO AUSTRAL - Precio x Kilo",
    "Jamon Crudo \"DESHUESADO\" - CAMPO AUSTRAL - Precio x Kilo",
    "Jamon Crudo - PARMESANO - Precio x Kilo",
    "Leberwurst - CAMPO AUSTRAL - Precio x unidad (200 Grs)",
    "Lomo a las Finas Hierbas - LARIO - Precio x Kilo",
    "Lomo Cocido Clasico - LARIO - Precio x Kilo",
    "Mortadela MINI - CAMPO AUSTRAL - Precio x unidad (300 Grs)",
    "Mortadela - LARIO - Precio x Kilo",
    "Mortadela con pistachos - LARIO - Precio x Kilo",
    "Panceta Ahumada - CAMPO AUSTRAL - Precio x Kilo",
    "Panceta Ahumada - SCUDETTO - Precio x Kilo",
    "Salchichon Primavera - Buenas Sierras - Precio x Kilo",
    "Longaniza Calabresa - Precio x Kilo",
    "Longaniza Calabresa - EL BIERZO - Precio x Kilo",
    "Cantimpalo - Buenas Sierras - Precio x Kilo",
    "Pepperoni - CAMPO AUSTRAL - Precio x Kilo",
    "Salame de Cerdo - CAMPO AUSTRAL - Precio x Kilo",
    "Salame a las Finas Hierbas - CAMPO AUSTRAL - Precio x Kilo",
    "Salame Milan Picado Fino LARIO - Precio x Kilo",
    "Salame tipo Milan - CAMPO AUSTRAL - Precio x Kilo",
    "Salame Milan Picado Fino 66 - Precio x Kilo",
    "Salame Fuet c/emplume - CAMPO AUSTRAL - Precio x unidad",
    "Salamin Picado Fino - CAMPO AUSTRAL - Precio x unidad",
    "Salamin Picado Grueso - CAMPO AUSTRAL - Precio x unidad",
    "Salchichas largas Gastronomicas - Chacra Nuestra (( pack x 18 unidades ))",
    "Hamburguesas linea resto BURGER CRAFT x 80 Gr ((caja x 60 unid))",
    "Hamburguesas linea resto BURGER CRAFT x 120 Gr ((caja x 40 unid))",
    "Hamburguesas linea resto BURGER CRAFTERS x 120 Gr ((caja x 160 unid))",
    "Hamburguesas linea resto BURGER CRAFT x 140 Gr ((caja x 36 unid))",
    "Hamburguesas linea resto BURGER CRAFT x 140 Gr ((caja x 96 unid))",
    "Hamburguesas linea CRAFT condimentadas BURGER CRAFT x 140 Gr ((caja x 36 unid))",
    "Hamburguesas linea CRAFT sin condimentos BURGER CRAFT x 120 Gr ((caja x 40 unid))",
    "Hamburguesas linea CRAFT sin condimentos BURGER CRAFT x 120 Gr ((caja x 160 unid))",
    "Milanesa de Pollo BURGER CRAFTER 160-170 Gr. ((caja x 2,5 Kg))",
    "Milanesa de Pollo BURGER CRAFTER 160-170 Gr. - productos seleccionados ((caja x 15 unid))",
    "Milanesa de Carne BURGER CRAFTER 160-170 Gr. ((caja x 2,5 Kg))",
    "Milanesa de Carne BURGER CRAFTER 160-170 Gr. - productos seleccionados ((caja x 15 unid))",
    "Milanesa de Peceto BURGER CRAFTERS ((caja x 2,5 Kg))",
    "Medallon de Pollo Crispy BURGER CRAFTER x 120 Gr (+/- 5 Gr) - ((caja x 30 unid))",
    "Nuggets de Pollo congelados BURGER CRAFTER x 15 Gr ((caja x 120 unid))",
    "Chicken Fingers BURGER CRAFTERS ((caja x 2,5 Kg))",
    "Chicken Fingers BURGER CRAFTERS - productos seleccionados ((caja x 60 unid))",
    "Muzzarellitas Crispy BURGER CRAFTERS ((caja x 2,5 Kg))",
    "Paty comercial (69 Gr) - ((( CAJA x 72 u )))",
    "Paty (80 Gr) ((( CAJA x 60 u )))",
    "Paty Super (125 Gr) ((( CAJA x 40 u )))",
    "Medallon NOTBURGER 80 Grs ((( CAJA x 62 u )))",
    "Papa baston Simplot Extra Crunch corte Tradicional (caja 6 u x 2,5 kg)",
    "Papa baston Simplot Extra Crunch corte Fino (caja 6 u x 2,5 kg)",
    "Papa baston Simplot corte Fino (caja 8 u x 2,25 kg)",
    "Papa baston Simplot corte Tradicional (caja 6 u x 2,5 kg)",
    "Papa baston Simplot corte Casero (caja 6 u x 2,5 kg)",
    "Papas Rusticas Simplot - Gajos con piel (caja 7 u x 2 kg)",
    "Guacamole Simplot (caja 12 u x 0,453 kg)",
    "Guacamole Simplot x 0,453 kg",
    "Pulpa de Palta Simplot (caja 12 u x 0,453 kg)",
    "Pulpa de Palta Simplot x 0,453 kg",
    "Aros de Cebolla Simplot (caja 10 u x 1,1 kg)",
    "Aros de Cebolla Simplot x 1,1 Kg",
    "Ananá cubeteado - IQF - FRESH - Bolsa x 1 Kg",
    "Arandanos - IQF - FRESH - Bolsa x 1 Kg",
    "Arandanos - IQF - ConoSud - Bolsa x 1 Kg",
    "Duraznos cubeteados/fetas - IQF - FRESH - Bolsa x 1 Kg",
    "Frambuesas enteras - IQF - FRESH - Bolsa x 1 Kg",
    "Frutillas medianas - IQF - FRESH - Bolsa x 1 Kg",
    "Frutillas medianas - IQF - Bolsa x 1 Kg",
    "Mango cubeteado - IQF - FRESH - Bolsa x 1 Kg",
    "Mix Frutos Rojos con Frutillas - IQF - FRESH - Bolsa x 1 Kg",
    "Mix Frutos Rojos SIN Frutillas - IQF - FRESH - Bolsa x 1 Kg",
    "Mix Frutos Rojos con Frutillas - IQF - JUMBALAY - Bolsa x 1 Kg",
    "Mix Frutos Rojos con Frutillas (GRANEL) - IQF - Bolson x 15 Kg",
    "Moras - IQF - FRESH - Bolsa x 1 Kg",
    "Pulpa de Açai congelada - FRESH - Bolsa x 1 Kg",
    "Pulpa de Lima congelada - FRESH - Bolsa x 1 Kg",
    "Pulpa de Mango congelada - GERGAL - Bolsa x 1 Kg",
    "Pulpa de Maracuya congelada con semillas - Bolsa x 1 Kg",
    "Pulpa de Maracuya congelada sin semillas - Bolsa x 1 Kg",
    "Acelga - IQF - ConoSud - Bolsa x 1 Kg (PF201304)",
    "Acelga - IQF - ConoSud - Bolsa x 2 Kg (PF201303)",
    "Arvejas - IQF - ConoSud - Bolsa x 1 Kg (PF200304)",
    "Arvejas - IQF - FRESH - Bolsa x 1 Kg",
    "Arvejas - IQF - ConoSud - Bolsa x 2,5 Kg (PF200303)",
    "Batata cubeteada - IQF - FRESH - Bolsa x 1 Kg",
    "Brocoli - IQF - ConoSud - Bolsa x 1 Kg",
    "Brocoli - IQF - FRESH - Bolsa x 1 Kg",
    "Brocoli (GRANEL) - IQF - Bolsa x 13 Kg",
    "Chaucha - IQF - FRESH - Bolsa x 1 Kg",
    "Chaucha - IQF - ConoSud - Bolsa x 1 Kg (PF200406)",
    "Chaucha - IQF - ConoSud - Bolsa x 2,5 Kg (PF200403)",
    "Cebolla cubeteada - IQF - FRESH - Bolsa x 1 Kg",
    "Cebolla en cubos - IQF - ConoSud - Bolsa x 1 Kg (PF201207)",
    "Cebolla en cubos - IQF - ConoSud - Bolsa x 2,5 Kg (PF201203)",
    "Choclo en granos - IQF - ConoSud - Bolsa x 1 Kg (PF200204)",
    "Choclo en granos - IQF - FRESH - Bolsa x 1 Kg",
    "Choclo en granos - IQF - ConoSud - Bolsa x 2,5 Kg (PF200203)",
    "Choclo en granos (GRANEL) - IQF - Bolsa x 15 Kg",
    "Choclo en granos (GRANEL) - IQF - Bolsa x 25 Kg",
    "Espinaca - IQF - FRESH - Bolsa x 1 Kg",
    "Espinaca - IQF - ConoSud - Bolsa x 1 Kg (PF200104)",
    "Espinaca - IQF - ConoSud - Bolsa x 2 Kg (PF200103)",
    "Espinaca (GRANEL) - IQF - Bolsa x 20 Kg",
    "Espinaca (GRANEL) - IQF - Bolsa x 25 Kg",
    "Mix Wok de Vegetales - IQF - FRESH - Bolsa x 1 Kg",
    "Mix Wok de Vegetales - IQF - ConoSud - Bolsa x 1 Kg (PF202203)",
    "Mix para Tacos - IQF - ConoSud - Bolsa x 1 Kg (PF202303)",
    "Mix Primavera - IQF - FRESH - Bolsa x 1 Kg",
    "Mix Primavera - IQF - ConoSud - Bolsa x 1 Kg (PF201005)",
    "Mix Relleno tarta Espinaca - IQF - ConoSud - Bolsa x 1 Kg (PF201803)",
    "Mix Relleno tarta Zucchini- IQF - ConoSud - Bolsa x 1 Kg (PF202103)",
    "Mix Tarta de Vegetales - IQF - FRESH - Bolsa x 1 Kg",
    "Pulpa de Palta - IQF - FRESH - Bolsa x 1 Kg",
    "Papa baston - IQF - Finca Balcarce - Bolsa x 2,5 Kg",
    "Morron rojo cubeteado - IQF - FRESH - Bolsa x 1 Kg",
    "Pimiento rojo en cubos - IQF - ConoSud - Bolsa x 1 Kg (PF200606)",
    "Remolacha en cubos - IQF - ConoSud - Bolsa x 1 Kg (PF202003)",
    "Zanahoria cubeteada - IQF - FRESH - Bolsa x 1 Kg",
    "Zanahoria en cubos - IQF - ConoSud - Bolsa x 1 Kg (PF200904)",
    "Zapallo cubeteado - IQF - FRESH - Bolsa x 1 Kg",
    "Zapallo en Cubos - IQF - ConoSud - Bolsa x 2,5 Kg",
    "Zucchini cubeteado - IQF - FRESH - Bolsa x 1 Kg",
]

def procesar(texto_ocr):
    prompt = f"""
Tu rol es actuar como un operador de Data Entry para una empresa gastronómica. Vas a estructurar facturas como una tabla con las siguientes columnas:
Fecha, Producto, Cantidad, Total, Local, Proveedor

* Fecha: Se encuentra en las primeras líneas del OCR, en formato de xx/xx/xxxx
* Producto: Es la "descripción" de cada uno de los productos. Cuando un producto diga "Descuento 10%" o solo "Descuento", ignora esa parte. En este campo solo nos sirve la descripción del producto, los descuentos estorban.
* Cantidad: Está al principio de cada línea de cada producto. Columna "Cant."
* Precio: Debes traerla vacía.
* Total: Corresponde a la columna "Subtotal (- Descuento)" de cada fila.
Son datos muy importantes, por favor no recortes ni resumas ninguna información. Debe ser precisamente lo que el OCR te mande, tu tarea es solo estructurar la información.
* Local: Corresponde al valor del campo "Cliente:"
* Proveedor: Siempre será "Jumbalay".
❗ No modifiques la información del OCR.
📍 El campo Local debe extraerse del texto si es posible.

**Formato CSV válido:**
- Importante: Sólo pueden haber las columnas antes mencionadas. No agregues columnas o romperás el formato de los procesos consiguientes.
- Todos los campos entre comillas dobles (").
- Separados por coma.
- Una línea por producto.
- Repetí la fecha si aparece solo una vez.
- No uses separadores de miles.
- Sin encabezado.

Texto OCR:
\"\"\"{texto_ocr}\"\"\"
"""


    resultado_csv = estructurar_con_prompt_especifico(prompt)

    if not resultado_csv or resultado_csv.strip() == "":
        print("⚠️ Gemini no devolvió datos útiles.")
        return None

    try:
        df = pd.read_csv(StringIO(resultado_csv), header=None)

        # Validación flexible de columnas
        if df.shape[1] == 7:
            df.columns = ["Fecha", "Producto", "Cantidad", "Precio", "Total", "Local", "Proveedor"]
        elif df.shape[1] == 6:
            df.columns = ["Fecha", "Producto", "Cantidad", "Total", "Local", "Proveedor"]
            df["Precio"] = ""
            df = df[["Fecha", "Producto", "Cantidad", "Precio", "Total", "Local", "Proveedor"]]
        else:
            print(f"❌ Estructura de columnas inesperada: {df.shape[1]} columnas")
            print(df.head())
            return None

        # Limpieza numérica robusta
        def limpiar_numero(valor):
            if pd.isna(valor):
                return 0.0
            valor_str = str(valor).replace("$", "").replace(" ", "").replace(".", "").replace(",", ".")
            return float(valor_str)

        df["Cantidad"] = df["Cantidad"].apply(limpiar_numero)
        df["Total"] = df["Total"].apply(limpiar_numero)

        # Calcular precio si está vacío
        if (df["Precio"] == "").all():
            df["Precio"] = (df["Total"] / df["Cantidad"]).round(2)

        # Filtrar filas sin producto o sin cantidad numérica
        df = df[df["Producto"].notna() & (df["Producto"].str.strip() != "")]
        df = df[df["Cantidad"] > 0]

        # Matchear nombre de producto si el score es suficiente
        def obtener_mejor_match(producto):
            match = process.extractOne(producto, articulos_validos, scorer=fuzz.token_sort_ratio)
            if match and match[1] >= 85:
                return match[0]
            else:
                return producto  # conservar original

        df["Producto"] = df["Producto"].apply(obtener_mejor_match)

        # Devolver solo las columnas esperadas
        return df[["Fecha", "Producto", "Cantidad", "Precio", "Total", "Local", "Proveedor"]]

    except Exception as e:
        print(f"❌ Error al procesar CSV en {__file__}: {e}")
        return None
